"""text

Revision ID: 4851018eda67
Revises: 
Create Date: 2020-11-26 22:57:04.856816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4851018eda67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mf_user',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='账户名'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='登录密码'),
    sa.Column('ip_address', sa.String(length=255), nullable=True, comment='登录IP'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mf_user_ip_address'), 'mf_user', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mf_user_ip_address'), table_name='mf_user')
    op.drop_table('mf_user')
    # ### end Alembic commands ###
