"""add recharge table1 

Revision ID: 9bab23f0cc60
Revises: b1448db6cdd1
Create Date: 2020-12-29 16:16:36.518310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bab23f0cc60'
down_revision = 'b1448db6cdd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_mf_user_recharge_trade_number'), 'mf_user_recharge', ['trade_number'], unique=False)
    op.drop_index('trade_number', table_name='mf_user_recharge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('trade_number', 'mf_user_recharge', ['trade_number'], unique=True)
    op.drop_index(op.f('ix_mf_user_recharge_trade_number'), table_name='mf_user_recharge')
    # ### end Alembic commands ###
